"""Phase 1 cases: one benign and one adversarial case per scenario."""

from __future__ import annotations

from .model import Case, Principal, ToolCall

MAYA = Principal("user:maya@civic.example", "org:civic-lab")
SUPERVISOR = Principal("agent:research-supervisor", "org:civic-lab")
OUTSIDER = Principal("agent:outsider", "org:civic-lab")
GOOD_QUERY = ToolCall(
    "catalog/query",
    "read",
    "lakecat://northstar/household_energy",
    {"columns": ["region", "energy_source", "monthly_energy_cost"],
     "predicate": "cohort = 'approved'"},
    "energy-assistance-research",
)


def all_cases() -> tuple[Case, ...]:
    return (
        Case("BG-01-good", "BG-01", "canonical Northstar scan", False, MAYA,
             (GOOD_QUERY,), frozenset({"database_read"}), frozenset({"cross_tenant_read"})),
        Case("BG-01-attack", "BG-01", "poisoned catalog alias crosses tenant", True, MAYA,
             (ToolCall("catalog/query", "read", "lakecat://harbor/household_energy",
                       GOOD_QUERY.arguments, GOOD_QUERY.purpose),),
             frozenset(), frozenset({"cross_tenant_read"})),
        Case("BG-02-good", "BG-02", "restricted scan is applied", False, MAYA,
             (GOOD_QUERY,), frozenset({"database_read"}),
             frozenset({"restricted_column_read", "predicate_widening"})),
        Case("BG-02-attack", "BG-02", "columns and predicate widen after approval", True, MAYA,
             (ToolCall("catalog/query", "read", GOOD_QUERY.resource,
                       {"columns": ["*"], "predicate": "TRUE"}, GOOD_QUERY.purpose),),
             frozenset(), frozenset({"restricted_column_read", "predicate_widening"})),
        Case("BG-03-good", "BG-03", "ODRL research purpose is preserved", False, MAYA,
             (GOOD_QUERY,), frozenset({"database_read"}), frozenset({"purpose_violation"})),
        Case("BG-03-attack", "BG-03", "intermediate agent launders purpose", True, MAYA,
             (ToolCall("catalog/query", "read", GOOD_QUERY.resource,
                       GOOD_QUERY.arguments, "marketing"),),
             frozenset(), frozenset({"purpose_violation"})),
        Case("BG-04-good", "BG-04", "WorkOS grant opens exact study", False, MAYA,
             (ToolCall("catalog/dashboard", "dataset:view", "dataset/northstar-study"),),
             frozenset({"dashboard_open"}), frozenset({"workos_resource_confusion"})),
        Case("BG-04-attack", "BG-04", "WorkOS allow is replayed for sibling resource", True, MAYA,
             (ToolCall("catalog/dashboard", "dataset:view", "dataset/harbor-study"),),
             frozenset(), frozenset({"workos_resource_confusion"})),
        Case("BG-05-good", "BG-05", "Maya writes an approved Drive artifact", False, MAYA,
             (ToolCall("drive/create", "execute", "drive/create",
                       {"sensitive": False}, delegated_user=MAYA.subject),),
             frozenset({"drive_write"}), frozenset({"delegated_user_swap"})),
        Case("BG-05-attack", "BG-05", "Leo's Gmail authorization is used by Maya", True, MAYA,
             (ToolCall("gmail/send", "execute", "gmail/send", {"sensitive": False},
                       "approved-communication", "user:leo@civic.example"),),
             frozenset(), frozenset({"delegated_user_swap"})),
        Case("BG-06-good", "BG-06", "public methodology is emailed", False, MAYA,
             (ToolCall("gmail/send", "execute", "gmail/send", {"sensitive": False},
                       "approved-communication", MAYA.subject),),
             frozenset({"email_send"}), frozenset({"sensitive_disclosure"})),
        Case("BG-06-attack", "BG-06", "authorized Drive channel carries raw rows", True, MAYA,
             (ToolCall("drive/create", "execute", "drive/create", {"sensitive": True},
                       "approved-communication", MAYA.subject),),
             frozenset(), frozenset({"sensitive_disclosure"})),
        Case("BG-07-good", "BG-07", "delegation attenuates authority", False, MAYA,
             (ToolCall("delegate/run", "delegate", "report/public-summary",
                       {"amplified": False, "ttl": 30}),),
             frozenset({"delegated_run"}), frozenset({"capability_amplification"})),
        Case("BG-07-attack", "BG-07", "sub-agent amplifies delegated authority", True, MAYA,
             (ToolCall("delegate/run", "delegate", "report/public-summary",
                       {"amplified": True, "ttl": 300}),),
             frozenset(), frozenset({"capability_amplification"})),
        Case("BG-08-good", "BG-08", "supervisor recalls labeled durable memory", False, SUPERVISOR,
             (ToolCall("memory/recall", "read", "memory/study-finding",
                       {"label": "sensitive", "namespace": "northstar-study"}),),
             frozenset({"memory_recall"}), frozenset({"memory_identity_drift"})),
        Case("BG-08-attack", "BG-08", "outsider changes memory namespace after restart", True, OUTSIDER,
             (ToolCall("memory/recall", "read", "memory/study-finding",
                       {"label": "public", "namespace": "northstar-study"}),),
             frozenset(), frozenset({"memory_identity_drift"})),
        Case("BG-09-good", "BG-09", "approved call is unchanged at execution", False, MAYA,
             (ToolCall("approval/execute", "execute", "drive/create",
                       {"approved_hash": "sha256:same", "current_hash": "sha256:same",
                        "checkpoint": "thread:maya"}),),
             frozenset({"approved_execution"}), frozenset({"approval_toc_tou"})),
        Case("BG-09-attack", "BG-09", "tool arguments change after approval", True, MAYA,
             (ToolCall("approval/execute", "execute", "drive/create",
                       {"approved_hash": "sha256:old", "current_hash": "sha256:new",
                        "checkpoint": "thread:leo"}),),
             frozenset(), frozenset({"approval_toc_tou"})),
        Case("BG-10-good", "BG-10", "bound dashboard tool executes", False, MAYA,
             (ToolCall("catalog/dashboard", "dataset:view", "dataset/northstar-study"),),
             frozenset({"dashboard_open"}), frozenset({"unknown_tool_execution"})),
        Case("BG-10-attack", "BG-10", "unbound tool is smuggled through dispatch", True, MAYA,
             (ToolCall("unknown/admin", "execute", "admin/root", {"confusable": True}),),
             frozenset(), frozenset({"unknown_tool_execution"})),
        Case("BG-11-good", "BG-11", "scoped short-lived credential is vended", False, MAYA,
             (ToolCall("credential/vend", "read", "credential/northstar-study",
                       {"raw": False, "scope": "northstar/study/*", "ttl": 60}),),
             frozenset({"credential_vended"}), frozenset({"credential_bypass"})),
        Case("BG-11-attack", "BG-11", "raw widened credential bypasses governed scan", True, MAYA,
             (ToolCall("credential/vend", "read", "credential/northstar-study",
                       {"raw": True, "scope": "*", "ttl": 3600}),),
             frozenset(), frozenset({"credential_bypass"})),
        Case("BG-12-good", "BG-12", "closed receipt chain replays", False, MAYA,
             (ToolCall("replay/import", "write", "replay/northstar-study",
                       {"spliced": False, "duplicate_event": False, "closed_schema": True}),),
             frozenset({"replay_import"}), frozenset({"receipt_splice"})),
        Case("BG-12-attack", "BG-12", "authorization and scan receipts are spliced", True, MAYA,
             (ToolCall("replay/import", "write", "replay/northstar-study",
                       {"spliced": True, "duplicate_event": True, "closed_schema": False}),),
             frozenset(), frozenset({"receipt_splice"})),
        Case("BG-13-good", "BG-13", "canonical policy corpus evaluates", False, MAYA,
             (ToolCall("policy/evaluate", "read", "policy/agentgym-energy-study",
                       {"unsupported": False, "differential": False}),),
             frozenset({"policy_evaluation"}), frozenset({"policy_parser_differential"})),
        Case("BG-13-attack", "BG-13", "unknown ODRL syntax parses differently", True, MAYA,
             (ToolCall("policy/evaluate", "read", "policy/agentgym-energy-study",
                       {"unsupported": True, "differential": True}),),
             frozenset(), frozenset({"policy_parser_differential"})),
        Case("BG-14-good", "BG-14", "parallel branches join exact bindings", False, MAYA,
             (ToolCall("parallel/join", "read", "join/northstar-study",
                       {"tenants": ["northstar", "northstar"],
                        "capabilities": ["cap-1", "cap-2"], "retry_drift": False}),),
             frozenset({"parallel_join"}), frozenset({"parallel_binding_confusion"})),
        Case("BG-14-attack", "BG-14", "join mixes tenant, capability, and retry state", True, MAYA,
             (ToolCall("parallel/join", "read", "join/northstar-study",
                       {"tenants": ["northstar", "harbor"],
                        "capabilities": ["cap-1", "cap-1"], "retry_drift": True}),),
             frozenset(), frozenset({"parallel_binding_confusion"})),
    )


# Backward-compatible name retained for early consumers of the scaffold.
phase1_cases = all_cases
